#!/bin/bash
gnuplot -persist <<-EOFMarker
set term postscript eps enhanced color
set output "vertex4_omega_0_nu.eps"
set pm3d at b
set multiplot layout 1, 1 title "3D surface of 4-leg vertex ({\Symbol n} {\Symbol n}' {\Symbol w} = 0.0)"
set dgrid3d 40,40
set xrange[-1.225:1.28]
set yrange[-1.225:1.28]
file_name1 = "vertex4_omega_0_nu.dat"
path_data1 = file_name1
#
set title "Real part"
splot path_data1 u 2:3:(\$4) with lines lw 1 lt 1 notitle

unset multiplot
EOFMarker
